### PR TITLE
Adds new client APIs for managing releases

### PR DESCRIPTION
**Pull request by ryanmoran**
new functionality includes:
- ExportRelease
- TaskResult
- Resource
- UploadRelease
- UploadStemcell

### CODE REVIEW

**Comment by ryanmoran** [comment]
Don't merge yet. We have some fixes we need to land first.

**Comment by gdean123** [comment]
@ryanmoran okay, let us know when it's ready

**Comment by ryanmoran** [comment]
It's ready! Merge at will.

**Comment by zankich** [comment]
Thanks! 🍦

**Pull request merged**
